name = "unduh-unduh"
main = "src/worker/index.ts"
compatibility_date = "2026-04-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true

[vars]
EXTRACTOR_TIMEOUT_MS = "60000"
MAX_BATCH_SIZE = "10"
MAX_UPSTREAM_CONCURRENCY = "1"

[[vpc_services]]
binding = "EXTRACTOR_VPC"
service_id = "019dd24a-3c3e-7260-854e-0297f46dc5a5"
remote = true
